# Generated by Django 5.2.5 on 2025-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
