# Generated by Django 5.2.5 on 2025-10-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classs', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
